### ISSUE TITLE
ReferenceError: Image is not defined

### ISSUE THREAD

**Issue by mivanov-dev** [pqina/ngx-filepond#28]
**Hello guys,**

**I have a problem with angular universal and filepond-plugin-image-exif-orientation when I try to build an application.**
**Although I added that:**
global['Image'] = window.Image;

**The error message is:**
var testImage = new Image();
                  ^
ReferenceError: Image is not defined
    at C:\Users\username\Documents\angular-angularmaterial\dist\server\main.js:234494:19
    at C:\Users\username\Documents\angular-angularmaterial\dist\server\main.js:234397:25
    at Object../node_modules/filepond-plugin-image-exif-orientation/dist/filepond-plugin-image-exif-orientation.js (C:\Users\username\Documents\angular-angularmaterial\dist\server\main.js:234399:3)
    at __webpack_require__ (C:\Users\username\Documents\angular-angularmaterial\dist\server\main.js:20:30)
    at Object../src/app/shared/modules/filepond.module.ts (C:\Users\username\Documents\angular-angularmaterial\dist\server\main.js:442727:50)
    at __webpack_require__ (C:\Users\username\Documents\angular-angularmaterial\dist\server\main.js:20:30)
    at Object../src/app/shared/modules/index.ts (C:\Users\username\Documents\angular-angularmaterial\dist\server\main.js:442770:22)
    at __webpack_require__ (C:\Users\username\Documents\angular-angularmaterial\dist\server\main.js:20:30)
    at Object../src/app/shared/shared.module.ts (C:\Users\username\Documents\angular-angularmaterial\dist\server\main.js:443108:19)
    at __webpack_require__ (C:\Users\username\Documents\angular-angularmaterial\dist\server\main.js:20:30)
    at Object../src/app/app.module.ts (C:\Users\username\Documents\angular-angularmaterial\dist\server\main.js:441503:25)
    at __webpack_require__ (C:\Users\username\Documents\angular-angularmaterial\dist\server\main.js:20:30)
    at Object../src/app/app.server.module.ts (C:\Users\username\Documents\angular-angularmaterial\dist\server\main.js:441628:22)
    at __webpack_require__ (C:\Users\username\Documents\angular-angularmaterial\dist\server\main.js:20:30)
    at Object../src/main.server.ts (C:\Users\username\Documents\angular-angularmaterial\dist\server\main.js:445505:27)
    at __webpack_require__ (C:\Users\username\Documents\angular-angularmaterial\dist\server\main.js:20:30)

**Comment by rikschennink** [comment]
Should be fixed in `1.0.8`, just published. Please confirm.

**Comment by mivanov-dev** [comment]
Thanks 😉
